translations = {
    "en": {
        "title": "Medical Diagnosis System",
        "diagnose": "Diagnose",
        "export": "Export PDF",
        "chart": "Show Chart",
        "clear": "Clear",
        "save": "Save Results",
        "close": "Close",
        "language_select": "Language:",
        "search_symptoms": "Search symptoms:",
        "warning": "Warning",
        "error": "Error",
        "success": "Success",
        "info": "Info",
        "no_symptoms_selected": "Please select at least one symptom.",
        "result": "Result",
        "no_disease_match": "No disease matched confidently based on selected symptoms.",
        "diagnosis_result": "Diagnosis Result",
        "diagnosis_result_header": "Potential conditions based on symptoms:",
        "run_diagnosis_first": "Please run the diagnosis first.",
        "confidence_percent": "Confidence %",
        "diagnosis_confidence": "Diagnosis Confidence",
        "diagnosis_chart_title": "Diagnosis Chart",
        "reportlab_missing": "ReportLab library is not installed. PDF export disabled.",
        "no_results_to_export": "No diagnosis results to export.",
        "save_report_as": "Save Report As...",
        "diagnosis_report": "Diagnosis Report",
        "selected_symptoms_label": "Selected Symptoms:",
        "none": "None",
        "diagnosis_results_label": "Diagnosis Results:",
        "advice_label": "Advice",
        "report_exported_to": "Report exported to",
        "pdf_export_error": "Failed to export PDF",
        "no_results_to_save": "No diagnosis results to save.",
        "save_results_as": "Save Results As...",
        "results_saved_success": "Results saved successfully.",
        "save_results_error": "Failed to save results",
        "selections_cleared": "Symptom selections cleared.",
        
        # Language names
        "lang_en": "English",
        "lang_es": "Spanish",
        "lang_fr": "French",
        
        # Categories
        "Respiratory": "Respiratory",
        "Gastrointestinal": "Gastrointestinal",
        "General": "General",
        "Neurological": "Neurological",
        "Metabolic": "Metabolic",
        
        # Disease Names
        "Flu": "Influenza",
        "COVID-19": "COVID-19",
        "Diabetes": "Diabetes Mellitus",
        "Hypertension": "Hypertension (High Blood Pressure)",
        "Migraine": "Migraine Headache",
        "Asthma": "Bronchial Asthma",
        "Tuberculosis": "Pulmonary Tuberculosis",
        "Malaria": "Malaria",
        "Depression": "Major Depressive Disorder",
        "Anxiety": "Generalized Anxiety Disorder",
        "Arthritis": "Rheumatoid Arthritis",
        "Gastritis": "Gastritis",
        "Pneumonia": "Pneumonia",
        "Hepatitis": "Viral Hepatitis",
        
        # Advice Keys
        "advice_flu": "Rest, stay hydrated, and consult a doctor if symptoms persist.",
        "advice_covid": "Isolate yourself, get tested, and consult a healthcare provider.",
        "advice_diabetes": "Monitor blood sugar levels and consult an endocrinologist.",
        "advice_hypertension": "Reduce salt intake, exercise regularly, and consult a doctor.",
        "advice_migraine": "Avoid triggers, rest in a dark room, and take prescribed medication.",
        "advice_asthma": "Use prescribed inhalers, avoid triggers, and seek medical help for severe attacks.",
        "advice_tuberculosis": "Follow a complete course of antibiotics as prescribed by a doctor.",
        "advice_malaria": "Take antimalarial medications and use preventive measures in endemic areas.",
        "advice_depression": "Seek therapy, consider medication if recommended, and build a support network.",
        "advice_anxiety": "Practice relaxation techniques, consider therapy, and follow medical advice.",
        "advice_arthritis": "Take prescribed anti-inflammatory medication and engage in gentle exercise.",
        "advice_gastritis": "Avoid spicy/acidic foods, take prescribed medication, and eat smaller meals.",
        "advice_pneumonia": "Complete the prescribed antibiotic course and take plenty of rest.",
        "advice_hepatitis": "Rest adequately, avoid alcohol, and follow up with a hepatologist.",
        
        # Symptom Names
        "fever": "Fever",
        "cough": "Cough",
        "sore throat": "Sore Throat",
        "shortness of breath": "Shortness of Breath",
        "fatigue": "Fatigue",
        "headache": "Headache",
        "loss of taste or smell": "Loss of Taste or Smell",
        "nausea": "Nausea",
        "vomiting": "Vomiting",
        "diarrhea": "Diarrhea",
        "abdominal pain": "Abdominal Pain",
        "body aches": "Body Aches",
        "dizziness": "Dizziness",
        "blurred vision": "Blurred Vision",
        "sensitivity to light": "Sensitivity to Light",
        "confusion": "Confusion",
        "frequent urination": "Frequent Urination",
        "increased thirst": "Increased Thirst",
        "unexplained weight loss": "Unexplained Weight Loss",
        "extreme hunger": "Extreme Hunger"
    },
    "es": {
        "title": "Sistema de Diagnóstico Médico",
        "diagnose": "Diagnosticar",
        "export": "Exportar PDF",
        "chart": "Mostrar Gráfico",
        "clear": "Limpiar",
        "save": "Guardar",
        "close": "Cerrar",
        "language_select": "Idioma:",
        "search_symptoms": "Buscar síntomas:",
        "warning": "Advertencia",
        "error": "Error",
        "success": "Éxito",
        "info": "Información",
        "no_symptoms_selected": "Por favor seleccione al menos un síntoma.",
        "result": "Resultado",
        "no_disease_match": "Ninguna enfermedad coincidió con confianza según los síntomas seleccionados.",
        "diagnosis_result": "Resultado del Diagnóstico",
        "diagnosis_result_header": "Condiciones potenciales basadas en síntomas:",
        "run_diagnosis_first": "Por favor ejecute el diagnóstico primero.",
        "confidence_percent": "% Confianza",
        "diagnosis_confidence": "Confianza del Diagnóstico",
        "diagnosis_chart_title": "Gráfico de Diagnóstico",
        "reportlab_missing": "La biblioteca ReportLab no está instalada. Exportación a PDF deshabilitada.",
        "no_results_to_export": "No hay resultados de diagnóstico para exportar.",
        "save_report_as": "Guardar Informe Como...",
        "diagnosis_report": "Informe de Diagnóstico",
        "selected_symptoms_label": "Síntomas Seleccionados:",
        "none": "Ninguno",
        "diagnosis_results_label": "Resultados del Diagnóstico:",
        "advice_label": "Consejo",
        "report_exported_to": "Informe exportado a",
        "pdf_export_error": "Error al exportar PDF",
        "no_results_to_save": "No hay resultados de diagnóstico para guardar.",
        "save_results_as": "Guardar Resultados Como...",
        "results_saved_success": "Resultados guardados con éxito.",
        "save_results_error": "Error al guardar resultados",
        "selections_cleared": "Selecciones de síntomas limpiadas.",
        
        # Language names
        "lang_en": "Inglés",
        "lang_es": "Español",
        "lang_fr": "Francés",
        
        # Categories
        "Respiratory": "Respiratorio",
        "Gastrointestinal": "Gastrointestinal",
        "General": "General",
        "Neurological": "Neurológico",
        "Metabolic": "Metabólico",
        
        # Disease Names  
        "Flu": "Gripe",
        "COVID-19": "COVID-19",
        "Diabetes": "Diabetes Mellitus",
        "Hypertension": "Hipertensión (Presión Arterial Alta)",
        "Migraine": "Migraña",
        "Asthma": "Asma Bronquial",
        "Tuberculosis": "Tuberculosis Pulmonar",
        "Malaria": "Malaria",
        "Depression": "Trastorno Depresivo Mayor",
        "Anxiety": "Trastorno de Ansiedad Generalizada",
        "Arthritis": "Artritis Reumatoide",
        "Gastritis": "Gastritis",
        "Pneumonia": "Neumonía",
        "Hepatitis": "Hepatitis Viral",
        
        # Advice Keys
        "advice_flu": "Descanse, manténgase hidratado y consulte a un médico si los síntomas persisten.",
        "advice_covid": "Aíslese, hágase la prueba y consulte a un proveedor de atención médica.",
        "advice_diabetes": "Controle los niveles de azúcar en sangre y consulte a un endocrinólogo.",
        "advice_hypertension": "Reduzca la ingesta de sal, haga ejercicio regularmente y consulte a un médico.",
        "advice_migraine": "Evite los desencadenantes, descanse en una habitación oscura y tome la medicación prescrita.",
        "advice_asthma": "Use inhaladores recetados, evite los desencadenantes y busque ayuda médica para ataques graves.",
        "advice_tuberculosis": "Siga un curso completo de antibióticos según lo prescrito por un médico.",
        "advice_malaria": "Tome medicamentos antipalúdicos y use medidas preventivas en áreas endémicas.",
        "advice_depression": "Busque terapia, considere medicación si se recomienda, y construya una red de apoyo.",
        "advice_anxiety": "Practique técnicas de relajación, considere la terapia y siga el consejo médico.",
        "advice_arthritis": "Tome medicamentos antiinflamatorios recetados y participe en ejercicios suaves.",
        "advice_gastritis": "Evite alimentos picantes/ácidos, tome medicamentos recetados y coma comidas más pequeñas.",
        "advice_pneumonia": "Complete el curso de antibióticos recetado y descanse mucho.",
        "advice_hepatitis": "Descanse adecuadamente, evite el alcohol y haga seguimiento con un hepatólogo.",
        
        # Symptom Names
        "fever": "Fiebre",
        "cough": "Tos",
        "sore throat": "Dolor de Garganta",
        "shortness of breath": "Dificultad para Respirar",
        "fatigue": "Fatiga",
        "headache": "Dolor de Cabeza",
        "loss of taste or smell": "Pérdida del Gusto o del Olfato",
        "nausea": "Náuseas",
        "vomiting": "Vómitos",
        "diarrhea": "Diarrea",
        "abdominal pain": "Dolor Abdominal",
        "body aches": "Dolores Corporales",
        "dizziness": "Mareos",
        "blurred vision": "Visión Borrosa",
        "sensitivity to light": "Sensibilidad a la Luz",
        "confusion": "Confusión",
        "frequent urination": "Micción Frecuente",
        "increased thirst": "Sed Aumentada",
        "unexplained weight loss": "Pérdida de Peso Inexplicable",
        "extreme hunger": "Hambre Extrema"
    },
    "ur": {
        # Language basics
        "title": "طبی تشخیصی نظام",
        "diagnose": "تشخیص کریں",
        "export": "پی ڈی ایف برآمد کریں",
        "chart": "چارٹ دکھائیں",
        "clear": "صاف کریں",
        "save": "محفوظ کریں",
        "close": "بند کریں",
        "language_select": "زبان:",
        "search_symptoms": "علامات تلاش کریں:",
        "warning": "انتباہ",
        "error": "غلطی",
        "success": "کامیابی",
        "info": "معلومات",
        "no_symptoms_selected": "براہ کرم کم از کم ایک علامت منتخب کریں۔",
        "result": "نتیجہ",
        "no_disease_match": "منتخب علامات کی بنیاد پر کوئی بیماری اعتماد سے مماثل نہیں۔",
        "diagnosis_result": "تشخیصی نتیجہ",
        "diagnosis_result_header": "علامات کی بنیاد پر ممکنہ حالات:",
        "run_diagnosis_first": "براہ کرم پہلے تشخیص چلائیں۔",
        "confidence_percent": "اعتماد %",
        "diagnosis_confidence": "تشخیصی اعتماد",
        "diagnosis_chart_title": "تشخیصی چارٹ",
        "reportlab_missing": "ReportLab لائبریری انسٹال نہیں ہے۔ پی ڈی ایف برآمد غیر فعال ہے۔",
        "no_results_to_export": "برآمد کرنے کے لئے کوئی تشخیصی نتائج نہیں ہیں۔",
        "save_report_as": "رپورٹ کو محفوظ کریں بطور...",
        "diagnosis_report": "تشخیصی رپورٹ",
        "selected_symptoms_label": "منتخب علامات:",
        "none": "کوئی نہیں",
        "diagnosis_results_label": "تشخیصی نتائج:",
        "advice_label": "مشورہ",
        "report_exported_to": "رپورٹ کو برآمد کیا گیا",
        "pdf_export_error": "پی ڈی ایف برآمد میں ناکامی",
        "no_results_to_save": "محفوظ کرنے کے لئے کوئی تشخیصی نتائج نہیں ہیں۔",
        "save_results_as": "نتائج محفوظ کریں بطور...",
        "results_saved_success": "نتائج کامیابی سے محفوظ ہو گئے۔",
        "save_results_error": "نتائج محفوظ کرنے میں ناکامی",
        "selections_cleared": "علامات کی منتخب شدہ چیزیں صاف ہو گئیں۔",
        
        # Language names
        "lang_en": "انگریزی",
        "lang_es": "ہسپانوی",
        "lang_fr": "فرانسیسی",
        "lang_ur": "اردو",
        
        # Categories
        "Respiratory": "تنفسی",
        "Gastrointestinal": "معدے اور آنتوں",
        "General": "عام",
        "Neurological": "اعصابی",
        "Metabolic": "میٹابولک",
        
        # Disease Names
        "Flu": "انفلوئنزا",
        "COVID-19": "کوویڈ-19",
        "Diabetes": "ذیابیطس میلیٹس",
        "Hypertension": "ہائی بلڈ پریشر",
        "Migraine": "شقیقہ",
        "Asthma": "دمہ",
        "Tuberculosis": "ٹی بی",
        "Malaria": "ملیریا",
        "Depression": "ڈپریشن",
        "Anxiety": "اضطراب",
        "Arthritis": "گٹھیا",
        "Gastritis": "معدے کی سوزش",
        "Pneumonia": "نمونیا",
        "Hepatitis": "ہیپاٹائٹس",
        
        # Advice Keys
        "advice_flu": "آرام کریں، پانی پیتے رہیں، اور اگر علامات برقرار رہیں تو ڈاکٹر سے مشورہ کریں۔",
        "advice_covid": "خود کو الگ رکھیں، ٹیسٹ کروائیں، اور صحت کی دیکھ بھال کرنے والے سے مشورہ کریں۔",
        "advice_diabetes": "بلڈ شوگر کی نگرانی کریں اور اینڈوکرینولوجسٹ سے مشورہ کریں۔",
        "advice_hypertension": "نمک کا استعمال کم کریں، باقاعدگی سے ورزش کریں، اور ڈاکٹر سے مشورہ کریں۔",
        "advice_migraine": "محرکات سے بچیں، اندھیرے کمرے میں آرام کریں، اور تجویز کردہ دوا لیں۔",
        "advice_asthma": "تجویز کردہ انہیلرز استعمال کریں، محرکات سے بچیں، اور شدید حملوں کے لئے طبی مدد طلب کریں۔",
        "advice_tuberculosis": "ڈاکٹر کی تجویز کردہ اینٹی بائیوٹکس کا مکمل کورس لیں۔",
        "advice_malaria": "اینٹی میلیریل ادویات لیں اور وبائی علاقوں میں حفاظتی تدابیر استعمال کریں۔",
        "advice_depression": "تھراپی لیں، اگر سفارش کی جائے تو ادویات پر غور کریں، اور ایک سپورٹ نیٹ ورک بنائیں۔",
        "advice_anxiety": "آرام کی تکنیکیں استعمال کریں، تھراپی پر غور کریں، اور طبی مشورہ پر عمل کریں۔",
        "advice_arthritis": "تجویز کردہ اینٹی انفلیمیٹری ادویات لیں اور ہلکی ورزش میں مشغول رہیں۔",
        "advice_gastritis": "تیز/تیزابی کھانوں سے پرہیز کریں، تجویز کردہ ادویات لیں، اور چھوٹی کھانے کی وعدے کھائیں۔",
        "advice_pneumonia": "تجویز کردہ اینٹی بائیوٹک کورس مکمل کریں اور بھرپور آرام کریں۔",
        "advice_hepatitis": "مناسب آرام کریں، الکحل سے پرہیز کریں، اور ہیپاٹولوجسٹ کے ساتھ فالو اپ کریں۔",
        
        # Symptom Names
        "fever": "بخار",
        "cough": "کھانسی",
        "sore throat": "گلے میں خراش",
        "shortness of breath": "سانس کی تکلیف",
        "fatigue": "تھکاوٹ",
        "headache": "سر درد",
        "loss of taste or smell": "ذائقہ یا بو کا نقصان",
        "nausea": "متلی",
        "vomiting": "قے",
        "diarrhea": "اسہال",
        "abdominal pain": "پیٹ میں درد",
        "body aches": "جسم میں درد",
        "dizziness": "چکر آنا",
        "blurred vision": "دھندلی نظر",
        "sensitivity to light": "روشنی کی حساسیت",
        "confusion": "الجھن",
        "frequent urination": "بار بار پیشاب آنا",
        "increased thirst": "پیاس میں اضافہ",
        "unexplained weight loss": "غیر وضاحتی وزن میں کمی",
        "extreme hunger": "شدید بھوک",
        "chest pain": "سینے میں درد",
        "joint pain": "جوڑوں کا درد",
        "skin rash": "جلد پر خارش",
        "night sweats": "رات میں پسینہ آنا"
    },
    # Add more languages here
}

def get_translation(lang, key):
    """Get a translation for a key in the specified language, fallback to English."""
    # Fallback to English if language not found, then fallback to the key itself if key not found
    return translations.get(lang, translations.get("en", {})).get(key, key)

def available_languages():
    """Return a list of available language codes."""
    return list(translations.keys())